#
# Copyright (c) 2024 Joshua Watt
#
# SPDX-License-Identifier: MIT
"""Common code for language renderers"""

import os
import sys
from abc import ABC, abstractmethod
from pathlib import Path
from typing import (
    TYPE_CHECKING,
    Any,
    Dict,
    IO,
    Iterator,
    List,
    Optional,
    Tuple,
    cast,
)

import jinja2
import jinja2.runtime
from jinja2 import Environment, FileSystemLoader, TemplateRuntimeError
from markupsafe import Markup
from rdflib.namespace import SH

from ..model import SHACL2CODE
from ..version import VERSION

if TYPE_CHECKING:
    import argparse

    from ..model import Model

THIS_DIR = Path(__file__).parent


@jinja2.pass_context
def include_file(ctx: jinja2.runtime.Context, name: str) -> Markup:
    env = ctx.environment
    if env.loader is None:
        raise TemplateRuntimeError("Environment has no loader configured")
    return Markup(env.loader.get_source(env, name)[0])


class JinjaTemplateRender(ABC):
    """Base class for all language renderers using Jinja2 templates."""

    HELP: str = ""

    def __init__(self, args: Any) -> None:
        self.spdx_license: str = args.license

    def get_additional_render_args(self, model: "Model") -> Dict[str, Any]:
        return {}

    def get_extra_env(self) -> Dict[str, Any]:
        return {}

    @classmethod
    @abstractmethod
    def get_arguments(cls, parser: "argparse.ArgumentParser") -> None:
        raise NotImplementedError

    @abstractmethod
    def get_outputs(self) -> Iterator[Tuple[Path, Path, Dict[str, Any]]]:
        raise NotImplementedError

    def render(
        self,
        template: Path,
        output: IO[str],
        *,
        extra_env: Optional[Dict[str, Any]] = None,
        render_args: Optional[Dict[str, Any]] = None,
    ) -> None:
        if extra_env is None:
            extra_env = {}  # pragma: no cover
        if render_args is None:
            render_args = {}  # pragma: no cover

        def abort_helper(msg: str) -> None:
            raise TemplateRuntimeError(msg)

        env = Environment(loader=FileSystemLoader([template.parent, THIS_DIR.parent]))
        env_globals = cast(Dict[str, Any], env.globals)
        env_globals["abort"] = abort_helper
        env_globals["SHACL2CODE"] = SHACL2CODE
        env_globals["SH"] = SH
        env_globals["SHACL2CODE_VERSION"] = VERSION
        for k, v in extra_env.items():
            env_globals[k] = v
        jinja_template = env.get_template(template.name)

        rendered = jinja_template.render(
            disclaimer=f"This file was auto-generated by {os.path.basename(sys.argv[0])} {VERSION}. DO NOT MANUALLY MODIFY IT",
            spdx_license=self.spdx_license,
            **render_args,
        )

        output.write(rendered)
        if not rendered[-1] == "\n":
            output.write("\n")

    def output(self, model: "Model") -> None:
        """Render the provided model."""

        class ObjectList(object):
            def __init__(self, objs: List[Any]) -> None:
                self.__objs = objs

            def __iter__(self) -> Iterator[Any]:
                return iter(self.__objs)

            def get(self, _id: str) -> Any:
                for o in self.__objs:
                    if o._id == _id:
                        return o
                raise KeyError(f"Object with ID {_id} not found")

        def get_all_derived(cls: Any) -> List[str]:
            def _recurse(cls: Any) -> Any:
                result = set(cls.derived_ids)
                for r in cls.derived_ids:
                    result |= _recurse(classes.get(r))
                return result

            d = list(_recurse(cls))
            d.sort()
            return d

        def get_all_named_individuals(cls: Any) -> List[str]:
            ni_set = set(i._id for i in cls.named_individuals)

            for d in get_all_derived(cls):
                ni_set |= set(i._id for i in classes.get(d).named_individuals)

            ni_list = list(ni_set)
            ni_list.sort()
            return ni_list

        classes = ObjectList(model.classes)
        concrete_classes = ObjectList(
            list(c for c in model.classes if not c.is_abstract)
        )
        abstract_classes = ObjectList(list(c for c in model.classes if c.is_abstract))
        enums = ObjectList(model.enums)

        render_args: Dict[str, Any] = {
            "classes": classes,
            "concrete_classes": concrete_classes,
            "abstract_classes": abstract_classes,
            "enums": enums,
            "context": model.context,
            **self.get_additional_render_args(model),
        }

        env: Dict[str, Any] = {
            "get_all_derived": get_all_derived,
            "get_all_named_individuals": get_all_named_individuals,
            "include_file": include_file,
            **self.get_extra_env(),
        }

        for out, template, args in self.get_outputs():
            if str(out) == "-":
                self.render(
                    template,
                    sys.stdout,
                    extra_env=env,
                    render_args={**render_args, **args},
                )
            else:
                with open(out, "w") as f:
                    self.render(
                        template,
                        f,
                        extra_env=env,
                        render_args={**render_args, **args},
                    )


class BasicJinjaRender(JinjaTemplateRender):
    """
    Common Jinja Template Renderer

    Renderers that only use a single Jinja file can derive from this class. For
    example:

        @language("my-lang")
        class MyRendered(BasicJinjaRenderer):
            HELP = "Generates my-lang bindings"

            def __init__(self, args):
                super().__init__(args, PATH / TO / TEMPLATE)
    """

    def __init__(self, args: Any, template: Path) -> None:
        super().__init__(args)
        self.__output: Path = args.output
        self.__template: Path = template

    @classmethod
    def get_arguments(cls, parser: "argparse.ArgumentParser") -> None:
        parser.add_argument(
            "--output",
            "-o",
            type=Path,
            help="Output file or '-' for stdout",
            required=True,
        )

    def get_outputs(self) -> Iterator[Tuple[Path, Path, Dict[str, Any]]]:
        yield self.__output, self.__template, {}
